/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ed.davidnavarroc.tarea1;

//Librerias
import ed.davidnavarroc.tarea1.Celebracion;
import java.text.SimpleDateFormat;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author angel
 */
public class ListadoCelebraciones extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ListadoCelebraciones.class.getName());
    private Gestor gestor;//Referencia del gestor centralizado
    
    public void recibirGestor(Gestor gestor){//Método público para compartir la misma instancia con otras ventanas
        this.gestor = gestor;
    }
    
    //Función que carga las celebraciones ingresadas por el usuario
    private void cargarCelebraciones(){
        DefaultTableModel modeloTabla = (DefaultTableModel) tablaCelebraciones.getModel();//Obtiene el modelo de la tabla
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");//Define el formato para mostrar la fecha (día/mes/año)
        
        Iterator<Celebracion> iterarCelebrarciones = gestor.getCelebraciones().iterator();//Iterador para recorrer la lista de celebraciones
        //Mientras sigan habiendo datos, recorre cada celebración y la agrega como una fila e
        while (iterarCelebrarciones.hasNext()){
            Celebracion datoCelebracion = iterarCelebrarciones.next();
            modeloTabla.addRow(new Object[]{
                datoCelebracion.getId(),
                formatoFecha.format(datoCelebracion.getFecha()),//Fecha formateada como texto
                datoCelebracion.getDescripcion(),
                datoCelebracion.getPais()
            });
        }
    }
    /**
     * Creates new form ListadoCelebraciones
     */
    public ListadoCelebraciones(Gestor gestor) {
        this.gestor = gestor;
        initComponents();
        cargarCelebraciones();//Método invocado al cargar la ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCelebraciones = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaCelebraciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fecha", "Descripción", "País"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaCelebraciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCelebraciones;
    // End of variables declaration//GEN-END:variables
}
