/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ed.davidnavarroc.tarea1;

import java.util.Iterator;

/**
 *
 * @author angel
 */
public class Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());
    
    //Instancia de Gestor para centralizar la lógica y la gestión de las celebraciones
    private Gestor gestor = new Gestor();
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMenuLista = new javax.swing.JButton();
        btnMenuRegistrar = new javax.swing.JButton();
        btnMenuEditar = new javax.swing.JButton();
        btnMenuInvertir = new javax.swing.JButton();
        btnMenuOrdenarMerge = new javax.swing.JButton();
        btnMenuOrdenarInsercion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMenuLista.setText("Lista de celebraciones");
        btnMenuLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuListaActionPerformed(evt);
            }
        });

        btnMenuRegistrar.setText("Registar celebración");
        btnMenuRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuRegistrarActionPerformed(evt);
            }
        });

        btnMenuEditar.setText("Buscar/Editar celebración");
        btnMenuEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuEditarActionPerformed(evt);
            }
        });

        btnMenuInvertir.setText("Países invertidos");
        btnMenuInvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuInvertirActionPerformed(evt);
            }
        });

        btnMenuOrdenarMerge.setText("Ordenar MergeSort");
        btnMenuOrdenarMerge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuOrdenarMergeActionPerformed(evt);
            }
        });

        btnMenuOrdenarInsercion.setText("Ordenar Inserción");
        btnMenuOrdenarInsercion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuOrdenarInsercionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMenuEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(btnMenuRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(btnMenuLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuInvertir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuOrdenarMerge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuOrdenarInsercion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(513, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnMenuRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMenuLista, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMenuEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMenuInvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMenuOrdenarMerge, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenuOrdenarInsercion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Función que se ejecuta al presionar el botón Lista de celebraciones
    private void btnMenuListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuListaActionPerformed
        // TODO add your handling code here:
        ListadoCelebraciones ventanaLista = new ListadoCelebraciones(gestor);//Se crea una instancia de la ventana de la lista de las celebraciones
        //La ventana se hace visible y se centra
        ventanaLista.setVisible(true);
        ventanaLista.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnMenuListaActionPerformed

    //Función que se ejecuta al presionar el botón Registrar en el menú
    private void btnMenuRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuRegistrarActionPerformed
        // TODO add your handling code here:
        RegistroCelebraciones ventanaRegistro = new RegistroCelebraciones();//Se crea una instancia de la ventana de registro
        ventanaRegistro.setVisible(true);        //La ventana se hace visible
        ventanaRegistro.recibirGestor(gestor);   //Se envía el formulario de Registrar la instancia de Gestor
        ventanaRegistro.setLocationRelativeTo(null); //Se centra la ventana
    }//GEN-LAST:event_btnMenuRegistrarActionPerformed

    //Función que se ejecuta al presionar el botón de Editar/Buscar en el menú
    private void btnMenuEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuEditarActionPerformed
        // TODO add your handling code here:
        BuscarEditarCelebraciones ventanaBuscarEditar = new BuscarEditarCelebraciones(gestor); //Se crea una instancia de la ventana Buscar/Editar
        //La ventana se hace visible y se centra
        ventanaBuscarEditar.setVisible(true);
        ventanaBuscarEditar.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnMenuEditarActionPerformed

    
    private void btnMenuOrdenarMergeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuOrdenarMergeActionPerformed
        // TODO add your handling code here:
        OrdenarCelebracionesMerge ventanaOrdenar = new OrdenarCelebracionesMerge(gestor);
        ventanaOrdenar.setVisible(true);
        ventanaOrdenar.setLocationRelativeTo(null);
        
        
    }//GEN-LAST:event_btnMenuOrdenarMergeActionPerformed

    private void btnMenuInvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuInvertirActionPerformed
        // TODO add your handling code here:
        PaisesInvertidos ventanaPaisesInvertidos = new PaisesInvertidos(gestor);
        ventanaPaisesInvertidos.setVisible(true);
        ventanaPaisesInvertidos.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnMenuInvertirActionPerformed

    private void btnMenuOrdenarInsercionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuOrdenarInsercionActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnMenuOrdenarInsercionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenuEditar;
    private javax.swing.JButton btnMenuInvertir;
    private javax.swing.JButton btnMenuLista;
    private javax.swing.JButton btnMenuOrdenarInsercion;
    private javax.swing.JButton btnMenuOrdenarMerge;
    private javax.swing.JButton btnMenuRegistrar;
    // End of variables declaration//GEN-END:variables
}
