/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ed.davidnavarroc.tarea1;

//Librerias
import java.text.SimpleDateFormat;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author angel
 */
public class OrdernarCelebracionInsercion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OrdernarCelebracionInsercion.class.getName());
    private Gestor gestor;//Referencia del gestor centralizado
    /**
     * Creates new form OrdernarCelebracionInsercion
     */
    
    //Esta función implementa la inserción y carga las listas ordenadas
    public void cargarOrdenadasInsercion (){
        gestor.insertionSort(gestor.getCelebraciones());
        
         // Llama al método del gestor que realiza el ordenamiento por inserción sobre la lista de celebraciones
        DefaultTableModel modeloTabla = (DefaultTableModel) tablaOrdenarInsercion.getModel();//Modelo de la tabla
        SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy/MM/dd");//Formato de la fecha
        
        Iterator<Celebracion> iterarCelebrarciones = gestor.getCelebraciones().iterator(); //Iterador para recorrer la lista ordenada de celebraciones

        while (iterarCelebrarciones.hasNext()){// Recorre cada celebración y la agrega como fila en la tabla
            Celebracion datoCelebracion = iterarCelebrarciones.next();
             // Agrega una nueva fila a la tabla con los datos de la celebración
            modeloTabla.addRow(new Object[]{
                datoCelebracion.getId(),
                formatoFecha.format(datoCelebracion.getFecha()),//Fecha formateada
                datoCelebracion.getDescripcion(),
                datoCelebracion.getPais()
            });
        }
    }
    
    public OrdernarCelebracionInsercion(Gestor gestor) {//Método público para compartir la misma instancia con otras ventanas
        this.gestor = gestor;//Asigna la instancia del gestor recibida al atributo local de la clase
        initComponents();
        cargarOrdenadasInsercion ();//Invoca al método que ordena las celebraciones con inserción y las muestra en la tabla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaOrdenarInsercion = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaOrdenarInsercion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fecha", "Descripción", "País"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaOrdenarInsercion);

        jLabel1.setText("Inserción");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(361, 361, 361)
                        .addComponent(jLabel1)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaOrdenarInsercion;
    // End of variables declaration//GEN-END:variables
}