/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ed.davidnavarroc.tarea1;

//Librerias
import java.text.SimpleDateFormat;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author angel
 */
public class PaisesInvertidos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PaisesInvertidos.class.getName());
    private Gestor gestor;//Referencia del gestor centralizado
    /**
     * Creates new form PaisesInvertidos
     */
    
    //Función que carga todas la celebraciones en una tabla con su respectivo país invertido
    private void cargarPaisesInvertidos(){
        DefaultTableModel modeloTabla = (DefaultTableModel) tablaPaisesInvertidos.getModel();//Modelo de la tabla
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");//Formato de la fecha
        
        Iterator<Celebracion> iterarInvertido = gestor.getCelebraciones().iterator();//Iterador que recorre la lista de las celebraciones
        while (iterarInvertido.hasNext()){//Se recorre la lista de celebraciones y las agrega como filas a la tabla
            
            Celebracion datoCelebracion = iterarInvertido.next();
            // Agrega una fila a la tabla con los datos de la celebración, incluyendo el país invertido
            modeloTabla.addRow(new Object[]{
                datoCelebracion.getId(),
                formatoFecha.format(datoCelebracion.getFecha()),//Fecha formateada
                datoCelebracion.getDescripcion(),
                datoCelebracion.getPais(),
                datoCelebracion.invertirPaises()
            });
        }
    }
    
    public PaisesInvertidos(Gestor gestor) {//Método público para compartir la misma instancia con otras ventanas
        this.gestor = gestor;//Asigna la instancia del gestor recibida al atributo local de la clase
        initComponents();
        cargarPaisesInvertidos();//Invoca al método para cargar las celebraciones con sus respectivos países invertidos
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPaisesInvertidos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaPaisesInvertidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fecha", "Descripción", "País", "País invertido"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaPaisesInvertidos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPaisesInvertidos;
    // End of variables declaration//GEN-END:variables
}
